### ISSUE TITLE
npm install error on centos

### ISSUE THREAD

**Issue by peking2** [stomita/node-salesforce#11]
Any ideas why it occured? Thanks.

> node-expat@2.0.0 install /var/releases/20130823215226/node_modules/node-salesforce/node_modules/xml2json/node_modules/node-expat
> node-gyp rebuild

make: Entering directory `/var//releases/20130823215226/node_modules/node-salesforce/node_modules/xml2json/node_modules/node-expat/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
make: cc: Command not found
make: *** [Release/obj.target/expat/deps/libexpat/lib/xmlparse.o] Error 127
make: Leaving directory`/var/releases/20130823215226/node_modules/node-salesforce/node_modules/xml2json/node_modules/node-expat/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/packages/encap/node-v0.10.15/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 2.6.18-238.el5
gyp ERR! command "node" "/packages/encap/node-v0.10.15/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/releases/20130823215226/node_modules/node-salesforce/node_modules/xml2json/node_modules/node-expat
gyp ERR! node -v v0.10.15
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by jsullivanlive** [comment]
Sounds like development tools are not installed.  In RPM systems (CentOS) you can usually install them with this:

`yum groupinstall 'Development Tools'`

or if you actually only need gcc then you can do `yum install gcc`
