### ISSUE TITLE
Salesforce Password Expiry

### ISSUE THREAD

**Issue by sushantchavan** [stomita/node-salesforce#12]
Hello team,

With subsequent saleforce releases. The password seems to expire after every 3 months.

How can it be handled in the system?

**Comment by jsullivanlive** [comment]
You can use OAuth instead of password.  OAuth does not expire with the password, so you will not run into the same problem.

Salesforce docs for setup:
http://www.salesforce.com/us/developer/docs/api_rest/index_Left.htm#CSHID=quickstart_oauth.htm|StartTopic=Content%2Fquickstart_oauth.htm|SkinName=webhelp

Alternatively, you could change your password expiration policy in the security section of salesforce to never expire.

**Comment by sushantchavan** [comment]
I have to run a worker process so that it checks for changes on MySql table and immediately makes changes to my Salesforce data. OAuth wouldnt be usable in such a case. Is there a work around apart from the password expiration policy.

**Comment by jsullivanlive** [comment]
I use OAuth for exactly that.  The benefit is that you don't have to worry
about password changes and expirations.  Check out the permission for
`refresh` which allows the OAuth user to request a new session to use over
and over, allowing perpetual access to the user's data.

**Comment by stomita** [comment]
@sushantchavan ,

As @jsullivanlive mentioned already, you can use OAuth2 refresh token to establish connection in your case. Node-salesforce supports OAuth2 authorization code flow to get refresh token (In Salesforce, username and password flow doesn't issue refresh token) in following code :

``` javascript
var conn = new Connection({
  oauth2: {
     clientId: '<client_id>'
     clientSecret: '<client_secret>',
     redirectUri: '<redirect_uri>'
  }
});
conn.authorize(code, function(err, userInfo) {
  if (err) { return; }
  console.log(conn.instanceUrl);
  console.log(conn.accessToken);
  console.log(conn.refreshToken);
});
```

After obtaining refresh token, you can create connection instance by passing them in the constructor : 

``` javascript
var conn = new Connection({
  oauth2: {
     clientId: '<client_id>'
     clientSecret: '<client_secret>',
     redirectUri: '<redirect_uri>'
  },
  instanceUrl: '<instance_url>',
  accessToken: '<access_token>',
  refreshToken: '<refresh_token>'
});
```

Even if the access token is expired, it automatically refreshes the token when calling APIs if refresh token is passed to.
