### ISSUE TITLE
Syntax Help

### ISSUE THREAD

**Issue by sushantchavan** [stomita/node-salesforce#13]
Need some help in querying records with LookUp fields and Child objects. How should one write the column names in Method Chaining

**Comment by stomita** [comment]
You can specify a lookup field in `fields` arg in `SObject#find(conditions, fields)`, and `fields` can be represented as object keys with positive value (like mongoDB), or array or comma-separated string of field names. If you want to point field in lookup relationship, you can specify with relationship name with period before the field name.

For example, if you want query all opportunity names with each of account name information, you can do it by following queries:

``` javascript
conn.sobject('Opportunity').find({}, { Name: 1, 'Account.Name' : 1 }).execute(function(err, records) { ... });
conn.sobject('Opportunity').find({}, [ 'Name', 'Account.Name' ]).execute(function(err, records) { ... });
conn.sobject('Opportunity').find({}, "Name, Account.Name").execute(function(err, records) { ... });
```

More simply, you can use `SObject#select(fields)` for just setting fields to query:

``` javascript
conn.sobject('Opportunity').select({ Name: 1, 'Account.Name' : 1 }).execute(function(err, records) { ... });
conn.sobject('Opportunity').select([ 'Name', 'Account.Name' ]).execute(function(err, records) { ... });
conn.sobject('Opportunity').select("Name, Account.Name").execute(function(err, records) { ... });
```

According to child relationships, you can use `Query#include(childRelName)` to include child relationship. After the call it enters child query construction context, until the call of `end()` to exit the child query context.

``` javascript
conn.sobject("Contact")
  .select("Id, FirstName, LastName, Account.Id, Account.Name")
  .include("Cases") // include child relationship records in query result. 
     // after include() call, entering into the context of child query.
     .select("Id, Subject, Status")
     .where({ Status: 'New' })
     .orderby("CreatedDate", "DESC")
     .end() // be sure to call end() to exit child query context
  .where({ LastActivityDate : sf.Date.THIS_MONTH }) // This filtering condition is applied to "Contact" SObject.
  .limit(10)
  .execute(function(err, records) { ... });
```
