### ISSUE TITLE
Issues with "Connection queryMore"

### ISSUE THREAD

**Issue by stemail23** [stomita/node-salesforce#14]
The various different flavours of using nextRecordsUrl for large queries seem to be broken, as they call the Query constructor with a null config parameter which barfs on "this.select(config.fields);"

I'm trying to find a work around. Any thoughts?

**Comment by stomita** [comment]
Do you have any code to show the issue ? Gist is welcome.

**Comment by stemail23** [comment]
I can't provide sample code right now (I'll try to provide something later if needed), but, connection.js queryMore, line 344:

var query = new Query(this, null, locator);

attempts to call new Query with a null second parameter, which will _always_ fail in query.js constructor, line 34:

this.select(config.fields);

which attempts to access null.fields. This seems to imply to me that any call to queryMore will always fail, so to demonstrate the issue, simply perform a select that retrieved more than 2000 records, and then call connection.queryMore(result.nextRecordsUrl ... when  (!result.done). I've temporarily worked round this by changing query.js line 32 to:

} else if (config) {

but I don't know quite what the repercussions of this are exactly!

I also found that executing a query with { autoFetch : true } always failed after the first retrieve of 2000 records. My suspicion was that this was perhaps a related issue, but I have not actually looked into it at all!

Cheers!

**Comment by stemail23** [comment]
Wondered if you'd had a chance to look at this? 

The README.md example, with tiny modification, exhibits the issue:

var records = [];
conn.query("SELECT Id, Name FROM Account", function(err, result) {
  if (err) { return console.error(err); }
  console.log("total : " + result.totalSize);
  console.log("fetched : " + result.records.length);
  console.log("done ? : " + result.done);
  if (!result.done) {
    console.log("next records URL : " + result.nextRecordsUrl);
    conn.queryMore(result.nextRecordsUrl, function(err, result) { ... });
  }
});

**Comment by stomita** [comment]
I understand the problem and fix it in a few days.
