### ISSUE TITLE
is $exists in sql-builder correct?

### ISSUE THREAD

**Issue by bojand** [stomita/node-salesforce#15]
```
case "EXISTS":
      return [ field, value ? "=" : "!=", "null" ].join(" ");
```

This doesn't seem to work...
shouldn't it be something like:

`return [ field, value ? "!=" : "==", "null" ].join(" ");`?
if value is `true` (ie. `$exists: true`) check against `!= null` otherwise check `== null`?

Maybe I am not using it correctly, but I have for example:

`AccountId: { $exists: true }`

and it doesn't work when I would expect object to be returned. If I set it to `false` it does work.

**Comment by stomita** [comment]
Oops, the operator is inverted. Thanks for pointing out.

**Comment by bojand** [comment]
Just curious, will you publish 0.6.3 (with this fix) to npm? Thanks.

**Comment by stomita** [comment]
Just published, thanks.
