### ISSUE TITLE
Npm install node-salesforce not working

### ISSUE THREAD

**Issue by vikasmalhotra** [stomita/node-salesforce#16]
Getting the error:

gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\YouConnected
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! weird error 1
npm http 304 https://registry.npmjs.org/websocket-driver
npm ERR! not ok code 0

on doing npm install. Node version is mentioned in the error.

**Comment by draz** [comment]
What OS are you running? What .NET version is installed? I find that on Windows machines installing the latest .Net Studio (Express counts as well) solves the problem

**Comment by vikasmalhotra** [comment]
OS: Windows 7 .NET: not using.net, i want to use it for nodejs project. Does it require the .net framework to run? and if yes which version?

**Comment by stomita** [comment]
dup #21
