### ISSUE TITLE
Queries eventually always timeout.

### ISSUE THREAD

**Issue by avnunn** [stomita/node-salesforce#17]
I have been using node-salesforce to be the glue between our salesforce data and separate services. Problem I find is that after a while, a few hours, it seems like every request I attempt with `SObject#find(conditions, fields)` just never returns.

I have put in code for this to detect if the query has persisted for too long and attempt retrying the query. This seems to work till it it simply "timesout" over and over and over again.

I'd like to say this is an error in the way I am using the API. I see that the build is currently "failing." Are there any flags I can switch on in the API that enables some verbose logs that could be useful to diagnose the potential issue?

**Comment by stomita** [comment]
Not described in docs but it has debug option to output debug logs. Use `new sf.Connection({ logLevel: 'debug' })` to create a debug output enabled connection. It will output logs to standard out.

(The travis-ci status is failing simply because OAuth token scraping had become incomplete. I will fix it in near future.)

**Comment by avnunn** [comment]
Thanks for the fast reply.

I'm going to go ahead and turn that logLevel flag on and try to see if I can capture the problem.

Currently as it stands node-salesforce has been used to process hundreds of queries at a given second and it seems to handle that load just fine (as fine as the Salesforce REST API can that is).

I don't know if I am running into issues of Salesforce limiting/throttling me.
I'll post back with I can find.

Unfortunately the problem only seems to happen very rarely and only after having the same `Connection#login(username, password)` authentication connection for hours+.

**Comment by avnunn** [comment]
This seems to no longer happening and it could have just been a networking fluke on my end.
I'll go ahead and close this ticket as it never seemed to be a true issue.
