### ISSUE TITLE
Error install with npm

### ISSUE THREAD

**Issue by idanblich** [stomita/node-salesforce#21]
Hi , 
I got this error when trying to install with npm 1.3.14 + node 0.10.22 + Win7 : 
"...

1372 verbose false,C:\node\myapp\node_modules,C:\node\myapp\node_modules\node-salesforce\node_modules unbuild xml2json@0.3.2
1373 info postuninstall xml2json@0.3.2
1374 verbose about to build C:\node\myapp\node_modules\node-salesforce
1375 info C:\node\myapp\node_modules\node-salesforce unbuild
1376 info preuninstall node-salesforce@0.6.4
1377 info uninstall node-salesforce@0.6.4
1378 verbose true,C:\node\myapp\node_modules,C:\node\myapp\node_modules unbuild node-salesforce@0.6.4
1379 verbose C:\node\myapp\node_modules.bin,[object Object] binRoot
1380 info postuninstall node-salesforce@0.6.4
1381 error node-expat@2.0.0 install: `node-gyp rebuild`
1381 error Exit status 1
1382 error Failed at the node-expat@2.0.0 install script.
1382 error This is most likely a problem with the node-expat package,
1382 error not with npm itself.
1382 error Tell the author that this fails on your system:
1382 error     node-gyp rebuild
1382 error You can get their info via:
1382 error     npm owner ls node-expat
1382 error There is likely additional logging output above.
1383 error System Windows_NT 6.1.7601
1384 error command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "node-salesforce"
1385 error cwd C:\node\myapp
1386 error node -v v0.10.22
1387 error npm -v 1.3.14
1388 error code ELIFECYCLE
1389 verbose exit [ 1, true ]
"

TX.

**Comment by stomita** [comment]
Fixed in the latest (0.7.0)
