### ISSUE TITLE
Cannot Refresh Token

### ISSUE THREAD

**Issue by ghelton** [stomita/node-salesforce#22]
Hi all, I am attempting to refresh my accessToken using a refresh token, I've attempted to follow the docs but the connection is failing silently and the refresh event is never triggered. All of the parameters are valid as far as I can tell. Regular authentication seems to be working fine.

```
var oauthParams = {
    clientId: 'xxx',
    clientSecret: 'xxx',
    redirectUri: 'xxx'
};

function refreshAuth(refreshToken, accessToken) {

    var deferred = Q.defer();

    // console.log('creating connection with:', oauthParams);
    conn = new sf.Connection({
        oauth2: oauthParams,
        instanceUrl: 'https://na15.salesforce.com',
        accessToken: accessToken,
        refreshToken: refreshToken
    });

    conn.on('refresh', function(accessToken, res) {
        console.log('refresh complete:', accessToken);
        deferred.resolve(accessToken);
    }, function(err) {
        console.log('hidden err:', err);
    });

    return deferred.promise;
}
```

**Comment by stomita** [comment]
You need to call API at least one time to refresh the expired access token. Refresh event is fired when the refresh is done during API invocation. To refresh access token explicitly, use `OAuth2#refreshToken()`.

**Comment by ghelton** [comment]
Thanks I was able to call it explicitly, it currently returns the same access token which I passed in and I'm assuming once my token expires it will pass back a new one. 

```
//sf connection
var oauth2 = new sf.OAuth2({
    clientId: sfconfig.clientId,
    clientSecret: sfconfig.clientSecret,
    redirectUri: sfconfig.redirectUri
});

function refreshAuth(refreshToken, accessToken) {
    var deferred = Q.defer();
    oauth2.refreshToken(refreshToken, function(err, response) {
        deferred.resolve(res.access_token);
    });

    return deferred.promise;
}
```

In regards to your first answer, our only method of authorization currently is through the Connection.authorize() method, which requires the auth code. When I do try to make any calls using the old access_token the calls fail. Is the expectation that I handle the failure by refreshing anytime a call fails?
