### ISSUE TITLE
Unwanted files in your NPM package

### ISSUE THREAD

**Issue by jpmonette** [stomita/node-salesforce#25]
Hey, I invite you to update your NPM package. I think it contains some unwanted files that you may not want to share, like `test.sh`, `pipeline.sh`, `migration.sh` and also y our project folder `.sublime`. Some may contain sensible information.

**Comment by stomita** [comment]
Oops, it is definitely what I wouldn't like to share. It seems I forgot to set .npmignore in my publishing folder. Thanks for your notice.
