### ISSUE TITLE
Getting "Description", "Required" fields

### ISSUE THREAD

**Issue by jpmonette** [stomita/node-salesforce#26]
Hello @stomita,

First, thanks for this Node.js package. I'd like to get the Description and Required value of a particular field. If I do as followed in the documentation:

```
conn.sobject('Account').describe(function(err, meta) {
  if (err) { return console.error(err); }
  console.log(meta.fields);
});
```

I noticed that each field describe doesn't contain the `description` and `required` keys (and also a couple other keys available there http://www.salesforce.com/us/developer/docs/api_meta/Content/customfield.htm).

Is there a way to get them using the package or something to fix in my request?

Thanks.

**Comment by stomita** [comment]
The URL you pointed is Metadata API, and our `SObject#describe()` call use REST API. The describe call of REST API returns similar SObject metadata info, but a little different.

http://www.salesforce.com/us/developer/docs/api_rest/Content/dome_sobject_describe.htm

By the way, I may add support for Metadata API in next release.

**Comment by jpmonette** [comment]
I'll start using https://github.com/tstachl/metaforce for now to support my needs, I'll follow your repository in case there's an update related to that. 

If `metaforce` doesn't meet my requirement, I might fork `node-salesforce` and do a pull request if you don't mind to add support to it ;)! Thanks!
