### ISSUE TITLE
Blob download

### ISSUE THREAD

**Issue by akve** [stomita/node-salesforce#27]
Hi there! Could not find a way to download a blob (Attachment file content) properly - request to URLs like
https://na14.salesforce.com/services/data/v24.0/sobjects/Attachment/00P58000000JqEKEA0/Body
it's executed without **encoding:null** in request. I use sObject.retrieve function to get body. I've fixed that locally inside the module, but I'm pretty sure that was wrong way to do - and you can fix it better :)

**Comment by stomita** [comment]
The repo is not maintained any more. Use the successor JSforce instead.
