### ISSUE TITLE
Not reactivating the session with the refresh_token

### ISSUE THREAD

**Issue by fullofcaffeine** [stomita/node-salesforce#3]
The refresh_token flow doesn't seem to be working. After the OAuth token expires, it just fails silently and even if I provide the refresh_token, it does not work.

Any ideas?

**Comment by stomita** [comment]
To refresh token it requires clientId, clientSecret, and redirectUri in connection option. I found it doesn't callback when invalid connection option is specified. I'll fix it and change the document to avoid misconfiguration.

**Comment by stomita** [comment]
Fixed and updated the doc in 0.3.3.
