### ISSUE TITLE
Provide the user Id

### ISSUE THREAD

**Issue by 0cv** [stomita/node-salesforce#4]
Hi,

could you please extend the method Connection.prototype.authorize of the connection.js to provide after an authorize the User Id in the callback? It's stored in this parameter like for example:
"id":"https://login.salesforce.com/id/00Dd0000000dDhxEAF/005d0000000jI3AAAU"

**Comment by stomita** [comment]
Good idea.

**Comment by stomita** [comment]
From 0.4.0, it returns userInfo object which contains id and organizationId in successful login response. See README.md.
