### ISSUE TITLE
Bulkify

### ISSUE THREAD

**Issue by 0cv** [stomita/node-salesforce#5]
Is there a way to implement the bulk rest api in order to make CRUD operations in Bulk?

**Comment by stomita** [comment]
Planning. Currently only calling CRUD rest api in parallel.

**Comment by scotthovestadt** [comment]
I would also appreciate this.

**Comment by ivanstoyanov** [comment]
Bulk API support would be truly awesome.

**Comment by stomita** [comment]
From 0.5.0 it supports bulk API.
