### ISSUE TITLE
Please add a generic way to call the SOAP API.

### ISSUE THREAD

**Issue by 0cv** [stomita/node-salesforce#6]
This would be great if you could make a small enhancement to support custom build SOAP API Call. It's not about building the whole stuff by parsing the wsdl but rather this could be cool in a first step just to call a method like .genericSOAP to which we give the full SOAP request.

and then you build the http request, send the request, get the result and send it to a callback function. This would have also to support if the access token is still valid - and if not refreshing it. Actually this shouldn't be far away from the soap login / logout method you have already written, just more generic.

The point is that the REST API is cool but limited while the SOAP API is weird but offers lots of possibilities - and building ourself the request might be not that nice but it's still pretty easy.

**Comment by stomita** [comment]
I understand SOAP API has features which are not provided in current REST API. As for providing generic SOAP API wrapper, AJAX Toolkit did the very same work in browser world. We can do similar things in node-salesforce, but simple porting may raise a license issue (no OSS license in AJAX Toolkit). Additionally, I don't have so much appetite to port it to Node currently.
