### ISSUE TITLE
Support for convertLead SOAP API

### ISSUE THREAD

**Issue by bhang** [stomita/node-salesforce#8]
First off, thanks for putting this library out there, it has been immensely useful!

I know this is supposed to be a wrapper around the REST API but unfortunately, I don't think the REST API supports all the functions that are available through the SOAP API. Would it be possible to support some of the Core functions like convertLead: http://www.salesforce.com/us/developer/docs/api/Content/sforce_api_calls_convertlead.htm

thanks
-bhang

**Comment by stomita** [comment]
SOAP API is out of scope.
